@startuml BuilderPattern
skinparam legendFontSize 12

class Product

interface IBuilder {
  +BuildPartA()
  +BuildPartB()
  +GetResult(): Product
}

class ConcreteBuilder {
  +BuildPartA()
  +BuildPartB()
  +GetResult(): Product
}
IBuilder <|.. ConcreteBuilder

class Director {
  +Construct(): Product
}
class Client {
  +DoSomething()
}
Director --> IBuilder
ConcreteBuilder --> Product
Client --> Director : uses

legend left
  <|.. = interface realization
  -->  = usage
end legend
@enduml
