@startuml AbstractFactoryPattern

title Abstract Factory Pattern for Levels and Enemies

interface LevelFactory {
    + CreateCave(GameMapFactory mapFactory, GameEnemyMapFactory enemyFactory): ICave
    + CreateDungeon(GameMapFactory mapFactory, GameEnemyMapFactory enemyFactory): IDungeon
}

class GameMapFactory {
    + CreateCaveMap(int rows, int cols): string[,]
    + CreateDungeonMap(int rows, int cols): string[,]
}

class GameEnemyMapFactory {
    + CreateCaveEnemies(int rows, int cols): IMonster[,]
    + CreateDungeonEnemies(int rows, int cols): IMonster[,]
}

interface ICave {
    + string[,] CaveMap { get; }
    + IMonster[,] CaveEnemiesMap { get; }
}

interface IDungeon {
    + string[,] DungeonMap { get; }
    + IMonster[,] DungeonEnemiesMap { get; }
}

GameMapFactory ..> CaveMap : creates
GameMapFactory ..> DungeonMap : creates
GameEnemyMapFactory ..> CaveEnemies : creates
GameEnemyMapFactory ..> DungeonEnemies : creates


@enduml
