@startuml AbstractFactoryPattern
skinparam legendFontSize 12

interface AbstractFactory {
  +CreateProductA(): ProductA
  +CreateProductB(): ProductB
}
class ConcreteFactory1
class ConcreteFactory2
interface ProductA
interface ProductB


class ConcreteProductA1
class ConcreteProductB2
class ConcreteProductA2
class ConcreteProductB1


class Client {
  +DoSomething()
}
AbstractFactory <|.. ConcreteFactory1
AbstractFactory <|.. ConcreteFactory2
ProductA <|.. ConcreteProductA1
ProductB <|.. ConcreteProductB1
ProductA <|.. ConcreteProductA2
ProductB <|.. ConcreteProductB2
Client --> AbstractFactory : uses
ConcreteFactory1 ..> ConcreteProductA1 : creates
ConcreteFactory1 ..> ConcreteProductB1 : creates
ConcreteFactory2 ..> ConcreteProductA2 : creates
ConcreteFactory2 ..> ConcreteProductB2 : creates
Client ..> ProductA : uses
Client ..> ProductB : uses


@enduml
