name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Build site
      run: |
        # Ensure docs directory exists and copy main site files
        mkdir -p docs
        
        # Copy main website files to docs if they exist in root
        if [ -f index.html ]; then
          cp index.html docs/
        fi
        if [ -d assets ]; then
          cp -r assets docs/
        fi
        
        # List what we're deploying
        echo "Files to deploy:"
        ls -la docs/
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
